<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

return [
    'Количество пользователей:' => 'Número de Usuarios:',
    'Последним зарегистрировался:' => 'Ultimo Usuario Registrado:',
    'Тем:' => 'Temas:',
    'Сообщений:' => 'Mensajes:',
    'Тему создал:' => 'Tema Creado:',
    'написал' => 'escribió',
    'Сейчас на форуме:' => 'Online:',
    'гостей:' => 'Invitado:',
    'пользователей:' => 'Miembros ',
    'просмотров' => 'Vistas',
    'ответов' => 'Respuestas',
    'последним ответил' => 'Ultima Respuesta',
    'вопрос задал' => 'Pregunta de',
    'Новости' => 'Sección',
    'Автор' => 'Autor',
    'вернуться в раздел' => 'Regresar a: ',
    'в разделе' => 'Categoría',
    'Title' => 'Titulo',
    'Создать тему' => 'Crear Tema',
    'Отправить' => 'Guardar',
    'Напишите сообщение' => 'Escribir Mensaje',
    'Полужирный текст' => 'Negritas',
    'Курсивный текст' => 'Cursiva',
    'Зачеркнутый текст' => 'Tachado',
    'Отступ вправо' => 'Amentar Sangría',
    'Отступ влево' => 'Disminuir Sangría',
    'Вставка гиперссылки (URL)' => 'Insertar Hipervinculo (URL)',
    'Вставка картинки (URL)' => 'Insertar Imagen (URL)',
    'Список' => 'Viñetas',
    'Нумерованный список' => 'Numeración',
    'Цитата' => 'Comentarios',
    'Код' => 'Codigo',
    'Предпросмотр сообщения' => 'Vista Previa',
    'вас есть:' => "Usted Tiene:",
    'Упоминания' => 'Mencion(es)',
    'Вас упоминули в теме:' => 'Usted ha sido Mencionado en este Tema: ',
    'Нет новых уведомлений' => 'No hay Nuevas Menciones',
    'You Have' => 'Tu Tienes',
    'Notifications' => 'Notificaciones',
    'Тем' => 'Temas',
    'Сообщений' => 'Mensajes',
    'последнее Сообщений' => 'Ultimo Mensaje',
];