<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

return [
    'Количество пользователей:' => 'Número de Usuarios:',
    'Последним зарегистрировался:' => 'Ultimo Usuario Registrado:',
    'Тем:' => 'Temas:',
    'Сообщений:' => 'Mensajes:',
    'Тему создал:' => 'Tema Creado:',
    'написал' => 'escribió',
    'Сейчас на форуме:' => 'Online:',
    'гостей:' => 'Invitado:',
    'пользователей:' => 'Miembros ',
    'просмотров' => 'Mensajes',
    'ответов' => 'Respuestas',
    'последним ответил' => 'Ultima Respuesta',
    'вопрос задал' => 'Pregunta de',
    'Новости' => 'Noticias',
    'Автор' => 'Autor',
    'вернуться в раздел' => 'Regresar a: '
];